spring:
  application:
    name: payment-service
  profiles:
    active: none
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

  cloud:
    config:
      profile: ${PROFILE}

encrypt:
  key: ${ENCRYPT_KEY}